# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SafeEntry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSafeEntry.proto\x12\tSafeEntry\"\x1f\n\x07Request\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x14\n\x05Reply\x12\x0b\n\x03res\x18\x01 \x01(\x02\x32\xcf\x01\n\tSafeEntry\x12-\n\x03\x41\x64\x64\x12\x12.SafeEntry.Request\x1a\x10.SafeEntry.Reply\"\x00\x12-\n\x03Sub\x12\x12.SafeEntry.Request\x1a\x10.SafeEntry.Reply\"\x00\x12\x32\n\x08Multiply\x12\x12.SafeEntry.Request\x1a\x10.SafeEntry.Reply\"\x00\x12\x30\n\x06\x44ivide\x12\x12.SafeEntry.Request\x1a\x10.SafeEntry.Reply\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'SafeEntry_pb2'
  # @@protoc_insertion_point(class_scope:SafeEntry.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'SafeEntry_pb2'
  # @@protoc_insertion_point(class_scope:SafeEntry.Reply)
  })
_sym_db.RegisterMessage(Reply)

_SAFEENTRY = DESCRIPTOR.services_by_name['SafeEntry']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=30
  _REQUEST._serialized_end=61
  _REPLY._serialized_start=63
  _REPLY._serialized_end=83
  _SAFEENTRY._serialized_start=86
  _SAFEENTRY._serialized_end=293
# @@protoc_insertion_point(module_scope)
